name: whatsdone
description: Track your TODOs with WhatsDone

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^4.5.9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  provider: ^4.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "asset/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/logo.png